# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='產品描述'),
        ),
    ]
