# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.DeleteModel(
            name='Cart_Items',
        ),
    ]
